server:
  port: 8017

logging:
  level:
    ROOT: WARN
    az.kapitalbank.atlas: DEBUG

#management:
#  endpoints:
#    web:
#      exposure:
#        include: [ "env", "health", "info" ]

spring:
  application:
    name: ms-demo
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #issue with swagger & actuator
  cloud:
    vault:
      enabled: false
    consul:
      enabled: false

#resilience4j:
#  circuitbreaker:
#
#    instances:
#      withAnnotationCB:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 5
#        failureRateThreshold: 90
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 35s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 2
#        slidingWindowType: COUNT_BASED
#
#  retry:
#    instances:
#      withAnnotationCB:
#        maxRetryAttempts: 5
#        waitDuration: 3s


#resilience4j.timelimiter:
#  instances:
#    withAnnotationCB:
#      timeoutDuration: 3s

#esilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeoutDuration: 1000
#        cancelRunningFuture: true
#    instances:
#      timelimiterSlow:
#        baseConfig: default
#  bulkhead:
#    configs:
#      default:
#        maxConcurrentCalls: 5
#        maxWaitDuration: 0
#    instances:
#      greetingBulkhead:
#        baseConfig: default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always